/**
 * Topic-wise Yes/No question bank for Track-1 OJT (minimum 10 per topic).
 * Titles match ojt-topics-catalog seed topics.
 */

export type OjtYesNoAnswer = 'Yes' | 'No'

export type OjtYesNoQuestion = {
  id: string
  text: string
  answer: OjtYesNoAnswer
}

export type OjtTopicQuestionBank = {
  category: string
  topic: string
  questions: OjtYesNoQuestion[]
}

export const OJT_TOPIC_QUESTION_BANKS: OjtTopicQuestionBank[] = [
  {
    category: 'Motivation & job',
    topic: 'Why security job is important',
    questions: [
      { id: 'q01', text: 'Is a security guard’s main role to protect life, property and information?', answer: 'Yes' },
      { id: 'q02', text: 'Is the guard often the first face of the client and the company?', answer: 'Yes' },
      { id: 'q03', text: 'Can small habits like alertness and honesty prevent big losses?', answer: 'Yes' },
      { id: 'q04', text: 'Is a guard’s presence itself a deterrent to wrongdoers?', answer: 'Yes' },
      { id: 'q05', text: 'Is security work only for people who failed elsewhere?', answer: 'No' },
      { id: 'q06', text: 'Should a guard feel proud of the security profession?', answer: 'Yes' },
      { id: 'q07', text: 'Does polite and firm behaviour improve client trust?', answer: 'Yes' },
      { id: 'q08', text: 'Is sleeping on duty acceptable if the site is quiet?', answer: 'No' },
      { id: 'q09', text: 'Can one careless act harm the whole team’s reputation?', answer: 'Yes' },
      { id: 'q10', text: 'Should guards understand why the client pays for security?', answer: 'Yes' },
      { id: 'q11', text: 'Is ignoring a small safety risk always harmless?', answer: 'No' },
    ],
  },
  {
    category: 'Motivation & job',
    topic: 'Why OJT helps keep your posting',
    questions: [
      { id: 'q01', text: 'Does OJT mean On Site Tactical Training at the workplace?', answer: 'Yes' },
      { id: 'q02', text: 'Can regular OJT help reduce client complaints?', answer: 'Yes' },
      { id: 'q03', text: 'Is OJT only a punishment for bad guards?', answer: 'No' },
      { id: 'q04', text: 'Does attending OJT show the client that Agile invests in skill?', answer: 'Yes' },
      { id: 'q05', text: 'Can trained guards make fewer mistakes on duty?', answer: 'Yes' },
      { id: 'q06', text: 'Is skipping OJT without reason good for posting stability?', answer: 'No' },
      { id: 'q07', text: 'Should guards pay attention during OJT sessions?', answer: 'Yes' },
      { id: 'q08', text: 'Can good OJT performance be noticed by HOD and client?', answer: 'Yes' },
      { id: 'q09', text: 'Is OJT meant to support a guard’s career?', answer: 'Yes' },
      { id: 'q10', text: 'Should a guard treat OJT as a waste of time?', answer: 'No' },
      { id: 'q11', text: 'Does better skill from OJT help keep a posting?', answer: 'Yes' },
    ],
  },
  {
    category: 'Motivation & job',
    topic: 'How training helps client & company',
    questions: [
      { id: 'q01', text: 'Does training help the client get a safer site?', answer: 'Yes' },
      { id: 'q02', text: 'Can training reduce escalations for the company?', answer: 'Yes' },
      { id: 'q03', text: 'Is training part of Agile’s service delivery?', answer: 'Yes' },
      { id: 'q04', text: 'Does a trained team look more professional in audits?', answer: 'Yes' },
      { id: 'q05', text: 'Should training be blamed on the client’s “extra demand” only?', answer: 'No' },
      { id: 'q06', text: 'Can training improve SLA compliance?', answer: 'Yes' },
      { id: 'q07', text: 'Does learning today build client trust tomorrow?', answer: 'Yes' },
      { id: 'q08', text: 'Is refusing to learn new site rules helpful?', answer: 'No' },
      { id: 'q09', text: 'Can fewer incidents mean better company brand?', answer: 'Yes' },
      { id: 'q10', text: 'Should trainers link training benefits to both client and company?', answer: 'Yes' },
      { id: 'q11', text: 'Is untrained behaviour risk-free for Agile?', answer: 'No' },
    ],
  },
  {
    category: 'Motivation & job',
    topic: 'Discipline, punctuality & honesty',
    questions: [
      { id: 'q01', text: 'Should a guard come early for duty handover?', answer: 'Yes' },
      { id: 'q02', text: 'Is punctuality a form of respect for the next shift?', answer: 'Yes' },
      { id: 'q03', text: 'Is honesty required with cash, keys and material?', answer: 'Yes' },
      { id: 'q04', text: 'Is “small theft” acceptable if the amount is low?', answer: 'No' },
      { id: 'q05', text: 'Should post orders be followed even when no supervisor is watching?', answer: 'Yes' },
      { id: 'q06', text: 'Is sleeping on duty a discipline failure?', answer: 'Yes' },
      { id: 'q07', text: 'Should a found mobile phone be reported as per SOP?', answer: 'Yes' },
      { id: 'q08', text: 'Is covering up a mistake always better than reporting early?', answer: 'No' },
      { id: 'q09', text: 'Can one dishonest act end a security career?', answer: 'Yes' },
      { id: 'q10', text: 'Should guards report mistakes early to supervisors?', answer: 'Yes' },
      { id: 'q11', text: 'Is coming late every day without reason acceptable?', answer: 'No' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'Uniform & turnout',
    questions: [
      { id: 'q01', text: 'Must a guard wear full uniform as per post order?', answer: 'Yes' },
      { id: 'q02', text: 'Should shoes be polished and clothes neat on duty?', answer: 'Yes' },
      { id: 'q03', text: 'Is mixing civil clothes with uniform allowed on gate duty?', answer: 'No' },
      { id: 'q04', text: 'Is turnout part of the first impression for visitors?', answer: 'Yes' },
      { id: 'q05', text: 'Should name plate / ID be clean and visible?', answer: 'Yes' },
      { id: 'q06', text: 'Are slippers generally allowed on a formal gate post?', answer: 'No' },
      { id: 'q07', text: 'Should cap/beret be worn if the post order requires it?', answer: 'Yes' },
      { id: 'q08', text: 'Is dirty or torn uniform acceptable for client sites?', answer: 'No' },
      { id: 'q09', text: 'Should trainers check turnout respectfully?', answer: 'Yes' },
      { id: 'q10', text: 'Does good turnout show professionalism?', answer: 'Yes' },
      { id: 'q11', text: 'Can a guard hide the ID inside the pocket all day as normal practice?', answer: 'No' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'Personal grooming',
    questions: [
      { id: 'q01', text: 'Should hair and beard follow company / client rules?', answer: 'Yes' },
      { id: 'q02', text: 'Is clean appearance part of professional duty?', answer: 'Yes' },
      { id: 'q03', text: 'Should a guard use very strong perfume that distracts others?', answer: 'No' },
      { id: 'q04', text: 'Do clean nails matter for a professional look?', answer: 'Yes' },
      { id: 'q05', text: 'Is mocking a colleague’s appearance correct training practice?', answer: 'No' },
      { id: 'q06', text: 'Should grooming guidance be given respectfully?', answer: 'Yes' },
      { id: 'q07', text: 'Does grooming show self-respect and site respect?', answer: 'Yes' },
      { id: 'q08', text: 'Is a very untidy look acceptable at a corporate gate?', answer: 'No' },
      { id: 'q09', text: 'Should guards look alert, not casual, on duty?', answer: 'Yes' },
      { id: 'q10', text: 'Can poor grooming create a bad client impression?', answer: 'Yes' },
      { id: 'q11', text: 'Is grooming only needed on festival days?', answer: 'No' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'Personal hygiene on duty',
    questions: [
      { id: 'q01', text: 'Should a guard maintain personal hygiene before duty?', answer: 'Yes' },
      { id: 'q02', text: 'Is washing hands after washroom important?', answer: 'Yes' },
      { id: 'q03', text: 'Should the post area be kept clean?', answer: 'Yes' },
      { id: 'q04', text: 'Is spitting near the post acceptable?', answer: 'No' },
      { id: 'q05', text: 'Should fever or contagious illness be reported?', answer: 'Yes' },
      { id: 'q06', text: 'Is hiding illness and continuing duty always safe?', answer: 'No' },
      { id: 'q07', text: 'Should guards wash hands before eating on site when possible?', answer: 'Yes' },
      { id: 'q08', text: 'Is a dirty post a poor reflection on security?', answer: 'Yes' },
      { id: 'q09', text: 'Should hygiene counselling be done privately if sensitive?', answer: 'Yes' },
      { id: 'q10', text: 'Is personal hygiene linked to long duty comfort and health?', answer: 'Yes' },
      { id: 'q11', text: 'Can poor hygiene increase infection risk for others?', answer: 'Yes' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'Soft skills — polite & firm',
    questions: [
      { id: 'q01', text: 'Should a guard greet visitors politely?', answer: 'Yes' },
      { id: 'q02', text: 'Does “firm” mean shouting at visitors?', answer: 'No' },
      { id: 'q03', text: 'Can a guard be polite and still refuse unauthorised entry?', answer: 'Yes' },
      { id: 'q04', text: 'Should an angry visitor be matched with equal anger?', answer: 'No' },
      { id: 'q05', text: 'Is “Sir / Madam” appropriate professional language?', answer: 'Yes' },
      { id: 'q06', text: 'Should the guard call a supervisor if the situation escalates?', answer: 'Yes' },
      { id: 'q07', text: 'Is sarcasm a good soft skill at the gate?', answer: 'No' },
      { id: 'q08', text: 'Can clear simple language reduce arguments?', answer: 'Yes' },
      { id: 'q09', text: 'Should role-play of polite refusal be practised in OJT?', answer: 'Yes' },
      { id: 'q10', text: 'Is arguing loudly in front of other visitors professional?', answer: 'No' },
      { id: 'q11', text: 'Does calm tone help de-escalate tension?', answer: 'Yes' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'Mobile / social media rules',
    questions: [
      { id: 'q01', text: 'Is phone use for games and reels allowed on duty?', answer: 'No' },
      { id: 'q02', text: 'Should site photos be posted on social media without permission?', answer: 'No' },
      { id: 'q03', text: 'Are visitor lists and CCTV details confidential?', answer: 'Yes' },
      { id: 'q04', text: 'Should duty phones be used only as per post order?', answer: 'Yes' },
      { id: 'q05', text: 'Is taking lobby selfies for status updates allowed without approval?', answer: 'No' },
      { id: 'q06', text: 'Can phone distraction cause gate mistakes?', answer: 'Yes' },
      { id: 'q07', text: 'Should passwords and layouts be kept confidential?', answer: 'Yes' },
      { id: 'q08', text: 'Is sharing site problems on WhatsApp status professional?', answer: 'No' },
      { id: 'q09', text: 'Should trainers explain mobile misuse risks clearly?', answer: 'Yes' },
      { id: 'q10', text: 'Can unauthorised photography harm client trust?', answer: 'Yes' },
      { id: 'q11', text: 'Is collecting client staff personal numbers without need recommended?', answer: 'No' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'Visitor management',
    questions: [
      { id: 'q01', text: 'Should every visitor follow the entry process?', answer: 'Yes' },
      { id: 'q02', text: 'Must visitor name and purpose be recorded?', answer: 'Yes' },
      { id: 'q03', text: 'Can a “known person” skip the register always?', answer: 'No' },
      { id: 'q04', text: 'Should a visitor pass be issued and collected on exit?', answer: 'Yes' },
      { id: 'q05', text: 'If the host is unavailable, should the visitor wander alone inside?', answer: 'No' },
      { id: 'q06', text: 'Should time in and time out be recorded?', answer: 'Yes' },
      { id: 'q07', text: 'Is free entry without process allowed at a controlled site?', answer: 'No' },
      { id: 'q08', text: 'Should guards know the site’s visitor register fields?', answer: 'Yes' },
      { id: 'q09', text: 'Must ID type be checked as per SOP?', answer: 'Yes' },
      { id: 'q10', text: 'Should unescorted entry be prevented where escort is required?', answer: 'Yes' },
      { id: 'q11', text: 'Is visitor management only for VIP guests?', answer: 'No' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'Angry / irritated visitors',
    questions: [
      { id: 'q01', text: 'Should a guard stay calm with an angry visitor?', answer: 'Yes' },
      { id: 'q02', text: 'Is lowering your voice helpful in de-escalation?', answer: 'Yes' },
      { id: 'q03', text: 'Should the guard fight if the visitor shouts?', answer: 'No' },
      { id: 'q04', text: 'Is listening first a good step?', answer: 'Yes' },
      { id: 'q05', text: 'Should the guard explain the rule briefly and offer help?', answer: 'Yes' },
      { id: 'q06', text: 'Is matching anger with anger professional?', answer: 'No' },
      { id: 'q07', text: 'Should threats of violence be escalated as per SOP?', answer: 'Yes' },
      { id: 'q08', text: 'Can acknowledging the visitor’s hurry reduce tension?', answer: 'Yes' },
      { id: 'q09', text: 'Should personal insults be used to control the gate?', answer: 'No' },
      { id: 'q10', text: 'Is calling Control / HOD correct when the situation is unsafe?', answer: 'Yes' },
      { id: 'q11', text: 'Should role-play of angry visitor handling be practised?', answer: 'Yes' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'Access control (gate / restricted)',
    questions: [
      { id: 'q01', text: 'Should restricted areas be known to the post guard?', answer: 'Yes' },
      { id: 'q02', text: 'Is tailgating (one card, many people) a security risk?', answer: 'Yes' },
      { id: 'q03', text: 'Can a contractor enter a restricted zone without proof of authorisation?', answer: 'No' },
      { id: 'q04', text: 'When in doubt, should the guard stop politely and call the supervisor?', answer: 'Yes' },
      { id: 'q05', text: 'Is access control only for night shifts?', answer: 'No' },
      { id: 'q06', text: 'Should authorisation be by card / pass / list / escort as per post order?', answer: 'Yes' },
      { id: 'q07', text: 'Is allowing free movement into server rooms without checks correct?', answer: 'No' },
      { id: 'q08', text: 'Should trainers point out restricted zones on a site sketch when possible?', answer: 'Yes' },
      { id: 'q09', text: 'Does “I always go there” replace a valid pass?', answer: 'No' },
      { id: 'q10', text: 'Is one-card-one-person a good access practice?', answer: 'Yes' },
      { id: 'q11', text: 'Should unauthorised persons be challenged politely?', answer: 'Yes' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'VIP movement access control',
    questions: [
      { id: 'q01', text: 'Should VIP movement details be kept confidential?', answer: 'Yes' },
      { id: 'q02', text: 'Is advance intimation of VIP time and entry useful?', answer: 'Yes' },
      { id: 'q03', text: 'Should guards take selfies with VIP guests?', answer: 'No' },
      { id: 'q04', text: 'Must the route be kept clear for VIP movement?', answer: 'Yes' },
      { id: 'q05', text: 'Should VIP schedules be shared as gossip?', answer: 'No' },
      { id: 'q06', text: 'Is coordination with Control / protocol team important?', answer: 'Yes' },
      { id: 'q07', text: 'Should casual chatting block a VIP vehicle?', answer: 'No' },
      { id: 'q08', text: 'If VIP arrives early, should the guard inform the concerned person?', answer: 'Yes' },
      { id: 'q09', text: 'Is discreet handling part of VIP security?', answer: 'Yes' },
      { id: 'q10', text: 'Should media or curious staff be controlled politely?', answer: 'Yes' },
      { id: 'q11', text: 'Is VIP access control only the driver’s job?', answer: 'No' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'Frisking — method & respect',
    questions: [
      { id: 'q01', text: 'Should the reason for frisking be explained politely?', answer: 'Yes' },
      { id: 'q02', text: 'Must same-gender frisking be followed as per policy?', answer: 'Yes' },
      { id: 'q03', text: 'Is rough or joking behaviour during frisking acceptable?', answer: 'No' },
      { id: 'q04', text: 'Should frisking be methodical from head to toe as trained?', answer: 'Yes' },
      { id: 'q05', text: 'If a visitor refuses frisking, should entry be forced violently?', answer: 'No' },
      { id: 'q06', text: 'Should refusal be escalated to the supervisor as per SOP?', answer: 'Yes' },
      { id: 'q07', text: 'Are gadgets helpful where available for checking?', answer: 'Yes' },
      { id: 'q08', text: 'Is skipping lady visitor protocol allowed to save time?', answer: 'No' },
      { id: 'q09', text: 'Should dignity of the person be protected during frisking?', answer: 'Yes' },
      { id: 'q10', text: 'Can improper frisking create complaints and risk?', answer: 'Yes' },
      { id: 'q11', text: 'Is frisking only for suspicious-looking people and never for process?', answer: 'No' },
    ],
  },
  {
    category: 'Visitors & access',
    topic: 'Bag and material checking',
    questions: [
      { id: 'q01', text: 'Should bags be checked as per site SOP?', answer: 'Yes' },
      { id: 'q02', text: 'Must material outward match gate pass / invoice?', answer: 'Yes' },
      { id: 'q03', text: 'Can material leave without paperwork if the driver is known?', answer: 'No' },
      { id: 'q04', text: 'Should prohibited items be watched for during bag checks?', answer: 'Yes' },
      { id: 'q05', text: 'Is rough handling of personal items professional?', answer: 'No' },
      { id: 'q06', text: 'Should material movement be recorded in the register?', answer: 'Yes' },
      { id: 'q07', text: 'Are scanners / trays useful when available?', answer: 'Yes' },
      { id: 'q08', text: 'Should empty claims be verified by checking the vehicle / package?', answer: 'Yes' },
      { id: 'q09', text: 'Is sealing / stamping done as per site procedure when required?', answer: 'Yes' },
      { id: 'q10', text: 'Can skipping bag checks create theft or safety risk?', answer: 'Yes' },
      { id: 'q11', text: 'Should guards clear any material on verbal request alone without pass?', answer: 'No' },
    ],
  },
  {
    category: 'Vehicles',
    topic: 'Vehicle checking',
    questions: [
      { id: 'q01', text: 'Should vehicles be stopped and purpose asked at the gate?', answer: 'Yes' },
      { id: 'q02', text: 'Must driver ID and vehicle number be checked as per SOP?', answer: 'Yes' },
      { id: 'q03', text: 'Is standing directly in front of a moving vehicle safe?', answer: 'No' },
      { id: 'q04', text: 'Should boot / under-carriage checks be done as per site SOP?', answer: 'Yes' },
      { id: 'q05', text: 'Must vehicle entry/exit be logged?', answer: 'Yes' },
      { id: 'q06', text: 'Can occupants enter without matching authorisation?', answer: 'No' },
      { id: 'q07', text: 'Is an under-vehicle mirror useful where available?', answer: 'Yes' },
      { id: 'q08', text: 'Should greeting the driver be part of professional checking?', answer: 'Yes' },
      { id: 'q09', text: 'Is skipping vehicle checks during busy hours always correct?', answer: 'No' },
      { id: 'q10', text: 'Should unusual items in the vehicle be reported?', answer: 'Yes' },
      { id: 'q11', text: 'Does vehicle checking reduce site risk?', answer: 'Yes' },
    ],
  },
  {
    category: 'Vehicles',
    topic: 'Vehicle movement & parking',
    questions: [
      { id: 'q01', text: 'Should site traffic arrows and speed limits be followed?', answer: 'Yes' },
      { id: 'q02', text: 'Is parking in fire / emergency lanes allowed?', answer: 'No' },
      { id: 'q03', text: 'Should guards use clear hand signals to guide drivers?', answer: 'Yes' },
      { id: 'q04', text: 'Must abandoned or suspicious parked vehicles be reported?', answer: 'Yes' },
      { id: 'q05', text: 'Is arguing in the middle of the driveway professional?', answer: 'No' },
      { id: 'q06', text: 'Should emergency vehicle paths stay clear?', answer: 'Yes' },
      { id: 'q07', text: 'Can wrong parking block ambulance or fire tender?', answer: 'Yes' },
      { id: 'q08', text: 'Should rash driving near the gate be controlled?', answer: 'Yes' },
      { id: 'q09', text: 'Is vehicle movement control part of gate duty?', answer: 'Yes' },
      { id: 'q10', text: 'Should trainers practise basic traffic hand signals in OJT?', answer: 'Yes' },
      { id: 'q11', text: 'Can ignoring parking rules be accepted to please a VIP driver always?', answer: 'No' },
    ],
  },
  {
    category: 'Vehicles',
    topic: 'Material movement with vehicles',
    questions: [
      { id: 'q01', text: 'Is a gate pass required for loaded material vehicles as per SOP?', answer: 'Yes' },
      { id: 'q02', text: 'Should item count be verified against the pass?', answer: 'Yes' },
      { id: 'q03', text: 'Can a blank gate pass be signed in advance?', answer: 'No' },
      { id: 'q04', text: 'Must cabin and cargo be checked when “empty” is claimed?', answer: 'Yes' },
      { id: 'q05', text: 'Should exceptions go through stores / supervisor?', answer: 'Yes' },
      { id: 'q06', text: 'Is “manager told me” enough without a pass?', answer: 'No' },
      { id: 'q07', text: 'Does material vehicle control prevent theft?', answer: 'Yes' },
      { id: 'q08', text: 'Should inward and outward material be accounted for?', answer: 'Yes' },
      { id: 'q09', text: 'Can skipping paperwork create audit failure?', answer: 'Yes' },
      { id: 'q10', text: 'Should the guard refuse unauthorised loaded exit?', answer: 'Yes' },
      { id: 'q11', text: 'Is material movement only the storekeeper’s concern and never security’s?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'HOTO (handing / taking over)',
    questions: [
      { id: 'q01', text: 'Should the incoming guard come early for HOTO?', answer: 'Yes' },
      { id: 'q02', text: 'Must keys and devices be handed over properly?', answer: 'Yes' },
      { id: 'q03', text: 'Is only saying “OK” enough without briefing?', answer: 'No' },
      { id: 'q04', text: 'Should pending visitors and open issues be informed?', answer: 'Yes' },
      { id: 'q05', text: 'Must HOTO remarks be written and signed?', answer: 'Yes' },
      { id: 'q06', text: 'Should both guards walk the post when required?', answer: 'Yes' },
      { id: 'q07', text: 'Can the outgoing guard leave before the reliever is ready?', answer: 'No' },
      { id: 'q08', text: 'Are registers part of HOTO information?', answer: 'Yes' },
      { id: 'q09', text: 'Does poor HOTO create duty gaps and risk?', answer: 'Yes' },
      { id: 'q10', text: 'Should trainers show a good sample HOTO entry?', answer: 'Yes' },
      { id: 'q11', text: 'Is verbal handover without any record always enough for SLA sites?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'Registers & record keeping',
    questions: [
      { id: 'q01', text: 'Should register entries be clear with date and time?', answer: 'Yes' },
      { id: 'q02', text: 'Is overwriting without proper cancel/initial correct?', answer: 'No' },
      { id: 'q03', text: 'Must registers be filled during the shift, not only at month end?', answer: 'Yes' },
      { id: 'q04', text: 'Are registers treated as legal evidence?', answer: 'Yes' },
      { id: 'q05', text: 'Should blank pages be left for “later” as normal practice?', answer: 'No' },
      { id: 'q06', text: 'Do neat registers help in client audits?', answer: 'Yes' },
      { id: 'q07', text: 'Should guards know which registers their post uses?', answer: 'Yes' },
      { id: 'q08', text: 'Is false entry in a register a serious issue?', answer: 'Yes' },
      { id: 'q09', text: 'Can poor record keeping fail SLA checks?', answer: 'Yes' },
      { id: 'q10', text: 'Should corrections be a single line cancel with initial?', answer: 'Yes' },
      { id: 'q11', text: 'Are registers optional if CCTV exists?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'Incident reporting',
    questions: [
      { id: 'q01', text: 'Should incidents be reported early?', answer: 'Yes' },
      { id: 'q02', text: 'Must reports answer who, what, when, where and how?', answer: 'Yes' },
      { id: 'q03', text: 'Should serious incidents be informed to Control / supervisor immediately?', answer: 'Yes' },
      { id: 'q04', text: 'Is hiding a “small” incident always safe?', answer: 'No' },
      { id: 'q05', text: 'Should facts be written, not guesses?', answer: 'Yes' },
      { id: 'q06', text: 'Is disturbing evidence at a scene correct?', answer: 'No' },
      { id: 'q07', text: 'Should a written report follow an oral alert?', answer: 'Yes' },
      { id: 'q08', text: 'Can delayed reporting increase loss?', answer: 'Yes' },
      { id: 'q09', text: 'Should blame without facts be avoided?', answer: 'Yes' },
      { id: 'q10', text: 'Is incident reporting part of professional duty?', answer: 'Yes' },
      { id: 'q11', text: 'Can a guard decide alone that no report is needed for a theft?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'Patrolling & observation',
    questions: [
      { id: 'q01', text: 'Should patrol follow the route and timing in the post order?', answer: 'Yes' },
      { id: 'q02', text: 'Must locks, lights and unusual smells be checked?', answer: 'Yes' },
      { id: 'q03', text: 'Is patrolling only near the tea point enough?', answer: 'No' },
      { id: 'q04', text: 'Should anomalies be reported at once?', answer: 'Yes' },
      { id: 'q05', text: 'Must patrol be recorded in register / app as required?', answer: 'Yes' },
      { id: 'q06', text: 'Is a fully predictable patrol pattern always best?', answer: 'No' },
      { id: 'q07', text: 'Should night patrol be especially alert?', answer: 'Yes' },
      { id: 'q08', text: 'Can observation prevent incidents before they grow?', answer: 'Yes' },
      { id: 'q09', text: 'Should open windows / doors found odd be checked and reported?', answer: 'Yes' },
      { id: 'q10', text: 'Is purposeful patrol better than walking without looking?', answer: 'Yes' },
      { id: 'q11', text: 'Can skipping patrol on a quiet night be accepted as normal?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'Emergency communication',
    questions: [
      { id: 'q01', text: 'Should emergency numbers be kept ready at the post?', answer: 'Yes' },
      { id: 'q02', text: 'Must the message include location and what happened?', answer: 'Yes' },
      { id: 'q03', text: 'Is panic flooding on WhatsApp groups good practice?', answer: 'No' },
      { id: 'q04', text: 'Should Control be informed as per SOP in emergencies?', answer: 'Yes' },
      { id: 'q05', text: 'Is clear radio / phone communication important?', answer: 'Yes' },
      { id: 'q06', text: 'After calling, should the guard continue trained duty actions?', answer: 'Yes' },
      { id: 'q07', text: 'Can a vague message delay help?', answer: 'Yes' },
      { id: 'q08', text: 'Should critical numbers be repeated for clarity?', answer: 'Yes' },
      { id: 'q09', text: 'Is knowing whom to call in what order part of training?', answer: 'Yes' },
      { id: 'q10', text: 'Should Agile Control number be known to guards where applicable?', answer: 'Yes' },
      { id: 'q11', text: 'Is staying silent during an emergency acceptable?', answer: 'No' },
    ],
  },
  {
    category: 'Post & records (SLA)',
    topic: 'Security levels (Normal → Alert → High)',
    questions: [
      { id: 'q01', text: 'Are there different security levels such as Normal, Alert and High?', answer: 'Yes' },
      { id: 'q02', text: 'Should guards invent a High Alert without authority?', answer: 'No' },
      { id: 'q03', text: 'At Alert level, should checks become tighter?', answer: 'Yes' },
      { id: 'q04', text: 'Must guards execute the level declared by management / client?', answer: 'Yes' },
      { id: 'q05', text: 'Is Normal level the same as no duty at all?', answer: 'No' },
      { id: 'q06', text: 'At High level, may movement be more controlled as ordered?', answer: 'Yes' },
      { id: 'q07', text: 'Should trainers explain actions under each level?', answer: 'Yes' },
      { id: 'q08', text: 'Can understanding levels improve SLA response?', answer: 'Yes' },
      { id: 'q09', text: 'Is ignoring a declared Alert level allowed?', answer: 'No' },
      { id: 'q10', text: 'Should gate behaviour change when level rises?', answer: 'Yes' },
      { id: 'q11', text: 'Are security levels only for police and never for site guards?', answer: 'No' },
    ],
  },
  {
    category: 'Fire & bomb',
    topic: 'Fire drill & evacuation',
    questions: [
      { id: 'q01', text: 'Should people use the marked exit during fire alarm?', answer: 'Yes' },
      { id: 'q02', text: 'Is using a lift usually correct during fire if restricted?', answer: 'No' },
      { id: 'q03', text: 'Must the assembly point be known to guards?', answer: 'Yes' },
      { id: 'q04', text: 'Should personal belongings be collected before evacuating?', answer: 'No' },
      { id: 'q05', text: 'Is staying calm important during evacuation?', answer: 'Yes' },
      { id: 'q06', text: 'Should visitors be guided out as per SOP?', answer: 'Yes' },
      { id: 'q07', text: 'Can fighting a large fire alone without training be dangerous?', answer: 'Yes' },
      { id: 'q08', text: 'Should re-entry for bags be avoided until cleared?', answer: 'Yes' },
      { id: 'q09', text: 'Is knowing nearest exit part of OJT?', answer: 'Yes' },
      { id: 'q10', text: 'Must head-count be supported if assigned?', answer: 'Yes' },
      { id: 'q11', text: 'Is ignoring a fire alarm acceptable if it “seems like a drill”?', answer: 'No' },
    ],
  },
  {
    category: 'Fire & bomb',
    topic: 'Fire extinguisher points',
    questions: [
      { id: 'q01', text: 'Should every guard know nearby extinguisher locations?', answer: 'Yes' },
      { id: 'q02', text: 'Does PASS mean Pull, Aim, Squeeze, Sweep?', answer: 'Yes' },
      { id: 'q03', text: 'Can the wrong extinguisher type worsen some fires?', answer: 'Yes' },
      { id: 'q04', text: 'Should empty extinguishers be reported at once?', answer: 'Yes' },
      { id: 'q05', text: 'Is blocking an extinguisher with cartons acceptable?', answer: 'No' },
      { id: 'q06', text: 'Should extinguisher types on site be shown in training?', answer: 'Yes' },
      { id: 'q07', text: 'Is using an extinguisher without knowing the fire type risky?', answer: 'Yes' },
      { id: 'q08', text: 'Must damaged extinguishers be reported?', answer: 'Yes' },
      { id: 'q09', text: 'Are extinguisher points part of fire readiness?', answer: 'Yes' },
      { id: 'q10', text: 'Should trainers demonstrate PASS if safe and permitted?', answer: 'Yes' },
      { id: 'q11', text: 'Can extinguishers be borrowed for other uses like doorstops?', answer: 'No' },
    ],
  },
  {
    category: 'Fire & bomb',
    topic: 'Bomb threat call handling',
    questions: [
      { id: 'q01', text: 'Should the guard stay calm during a bomb threat call?', answer: 'Yes' },
      { id: 'q02', text: 'Must exact words and caller details be noted if possible?', answer: 'Yes' },
      { id: 'q03', text: 'Should the guard joke about bombs with colleagues?', answer: 'No' },
      { id: 'q04', text: 'Must Control / police be alerted as per SOP?', answer: 'Yes' },
      { id: 'q05', text: 'Should suspicious objects be touched after a threat?', answer: 'No' },
      { id: 'q06', text: 'Is keeping the caller talking (if safe) useful to gather information?', answer: 'Yes' },
      { id: 'q07', text: 'Should threat details be posted on social media?', answer: 'No' },
      { id: 'q08', text: 'Must evacuation follow official order / SOP?', answer: 'Yes' },
      { id: 'q09', text: 'Can background noise notes help investigators?', answer: 'Yes' },
      { id: 'q10', text: 'Should a printed checklist be used when available?', answer: 'Yes' },
      { id: 'q11', text: 'Is ignoring a threat call because it “sounds fake” correct?', answer: 'No' },
    ],
  },
  {
    category: 'Fire & bomb',
    topic: 'Suspicious bag / object',
    questions: [
      { id: 'q01', text: 'Should a suspicious bag be opened by the guard to check?', answer: 'No' },
      { id: 'q02', text: 'Is “observe – isolate – inform” the right approach?', answer: 'Yes' },
      { id: 'q03', text: 'Must the area be cordoned and people moved away?', answer: 'Yes' },
      { id: 'q04', text: 'Should the object be kicked aside?', answer: 'No' },
      { id: 'q05', text: 'Must Control / police be informed as per SOP?', answer: 'Yes' },
      { id: 'q06', text: 'Is size, colour and location useful in the report?', answer: 'Yes' },
      { id: 'q07', text: 'Should a crowd be gathered to look at the bag?', answer: 'No' },
      { id: 'q08', text: 'Can an unattended odd bag be a serious risk?', answer: 'Yes' },
      { id: 'q09', text: 'Should the first sighting time be noted?', answer: 'Yes' },
      { id: 'q10', text: 'Is touching wires on a suspicious object safe?', answer: 'No' },
      { id: 'q11', text: 'Must guards follow no-touch discipline for suspicious objects?', answer: 'Yes' },
    ],
  },
  {
    category: 'First aid',
    topic: 'First aid — heat stroke / sunstroke',
    questions: [
      { id: 'q01', text: 'Can heat stroke be a medical emergency?', answer: 'Yes' },
      { id: 'q02', text: 'Should the person be moved to shade and cooled?', answer: 'Yes' },
      { id: 'q03', text: 'Is giving alcohol a correct first aid for heat stroke?', answer: 'No' },
      { id: 'q04', text: 'Should medical help / Control be called for severe cases?', answer: 'Yes' },
      { id: 'q05', text: 'Are confusion and hot skin possible signs of heat stroke?', answer: 'Yes' },
      { id: 'q06', text: 'Should water be forced into an unconscious person?', answer: 'No' },
      { id: 'q07', text: 'Are water breaks important for outdoor summer posts?', answer: 'Yes' },
      { id: 'q08', text: 'Should the guard stay with the affected person until help comes?', answer: 'Yes' },
      { id: 'q09', text: 'Can ignoring early heat symptoms be dangerous?', answer: 'Yes' },
      { id: 'q10', text: 'Is loosening tight clothing helpful while cooling?', answer: 'Yes' },
      { id: 'q11', text: 'Should toothpaste be applied for heat stroke?', answer: 'No' },
    ],
  },
  {
    category: 'First aid',
    topic: 'First aid — snake bite',
    questions: [
      { id: 'q01', text: 'Should the victim be kept calm and still?', answer: 'Yes' },
      { id: 'q02', text: 'Is cutting and sucking the wound correct first aid?', answer: 'No' },
      { id: 'q03', text: 'Must the person be taken to hospital quickly?', answer: 'Yes' },
      { id: 'q04', text: 'Should tight jewellery near the bite be removed?', answer: 'Yes' },
      { id: 'q05', text: 'Is hunting the snake more important than getting medical help?', answer: 'No' },
      { id: 'q06', text: 'Should the limb be immobilised as trained?', answer: 'Yes' },
      { id: 'q07', text: 'Are local myths like tourniquet always safe?', answer: 'No' },
      { id: 'q08', text: 'Can a snake-bite description help doctors if seen safely?', answer: 'Yes' },
      { id: 'q09', text: 'Should Control / supervisor be informed?', answer: 'Yes' },
      { id: 'q10', text: 'Is delaying hospital care dangerous?', answer: 'Yes' },
      { id: 'q11', text: 'Should the wound be cut open to “drain poison”?', answer: 'No' },
    ],
  },
  {
    category: 'First aid',
    topic: 'First aid — dog / animal bite',
    questions: [
      { id: 'q01', text: 'Should the wound be washed with soap and running water?', answer: 'Yes' },
      { id: 'q02', text: 'Is applying mud or chilli on the wound correct?', answer: 'No' },
      { id: 'q03', text: 'Must animal bites be reported in the incident register?', answer: 'Yes' },
      { id: 'q04', text: 'Should medical advice on vaccination be taken?', answer: 'Yes' },
      { id: 'q05', text: 'Can a “small” bite still need medical attention?', answer: 'Yes' },
      { id: 'q06', text: 'Should the wound be covered with a clean cloth after washing?', answer: 'Yes' },
      { id: 'q07', text: 'Is ignoring a dog bite safe?', answer: 'No' },
      { id: 'q08', text: 'Can rabies risk make quick care important?', answer: 'Yes' },
      { id: 'q09', text: 'Should trainers stress hospital visit even if bleeding stops?', answer: 'Yes' },
      { id: 'q10', text: 'Is washing for several minutes recommended?', answer: 'Yes' },
      { id: 'q11', text: 'Should tobacco be packed into the bite wound?', answer: 'No' },
    ],
  },
  {
    category: 'First aid',
    topic: 'First aid — bleeding, burns, fainting',
    questions: [
      { id: 'q01', text: 'Should firm pressure with a clean cloth be used for bleeding?', answer: 'Yes' },
      { id: 'q02', text: 'Is toothpaste or oil correct on burns?', answer: 'No' },
      { id: 'q03', text: 'Should burns be cooled with clean running water?', answer: 'Yes' },
      { id: 'q04', text: 'For fainting with no injury, can legs be raised as trained?', answer: 'Yes' },
      { id: 'q05', text: 'Should deeply stuck objects be pulled out immediately by the guard?', answer: 'No' },
      { id: 'q06', text: 'Must the first-aid box location be known?', answer: 'Yes' },
      { id: 'q07', text: 'Should gloves be used if available to avoid infection?', answer: 'Yes' },
      { id: 'q08', text: 'Is checking breathing important for a fainted person?', answer: 'Yes' },
      { id: 'q09', text: 'Should help be called for serious bleeding or burns?', answer: 'Yes' },
      { id: 'q10', text: 'Can wrong home remedies worsen burns?', answer: 'Yes' },
      { id: 'q11', text: 'Is leaving a heavily bleeding person alone without calling help correct?', answer: 'No' },
    ],
  },
  {
    category: 'Travel & special duty',
    topic: 'Travel safety with women employees',
    questions: [
      { id: 'q01', text: 'Must behaviour with women employees stay professional?', answer: 'Yes' },
      { id: 'q02', text: 'Should personal comments be avoided?', answer: 'Yes' },
      { id: 'q03', text: 'Is sharing a lady employee’s personal details allowed?', answer: 'No' },
      { id: 'q04', text: 'Should allotted route and timing be followed?', answer: 'Yes' },
      { id: 'q05', text: 'Are well-lit routes preferred when possible?', answer: 'Yes' },
      { id: 'q06', text: 'If the route feels unsafe, should Control be called?', answer: 'Yes' },
      { id: 'q07', text: 'Should unnecessary stops be avoided?', answer: 'Yes' },
      { id: 'q08', text: 'Is sitting against travel protocol acceptable?', answer: 'No' },
      { id: 'q09', text: 'Does respect and dignity matter during escort duty?', answer: 'Yes' },
      { id: 'q10', text: 'Should status be shared with Control when required by SOP?', answer: 'Yes' },
      { id: 'q11', text: 'Can casual joking about the traveller be unprofessional?', answer: 'Yes' },
    ],
  },
  {
    category: 'Travel & special duty',
    topic: 'Protect your traveller',
    questions: [
      { id: 'q01', text: 'Is traveller safety the first priority on escort duty?', answer: 'Yes' },
      { id: 'q02', text: 'Should pickup and drop points be known in advance?', answer: 'Yes' },
      { id: 'q03', text: 'Is disclosing traveller schedule to strangers allowed?', answer: 'No' },
      { id: 'q04', text: 'Must surroundings be watched while boarding / alighting?', answer: 'Yes' },
      { id: 'q05', text: 'Should the traveller be left alone in a dark parking area?', answer: 'No' },
      { id: 'q06', text: 'Is coordination with the driver important?', answer: 'Yes' },
      { id: 'q07', text: 'Should bag / laptop awareness be practised at the kerb?', answer: 'Yes' },
      { id: 'q08', text: 'Can ego be placed above traveller safety?', answer: 'No' },
      { id: 'q09', text: 'Should alternate routes be known when possible?', answer: 'Yes' },
      { id: 'q10', text: 'Is checking before opening the car door part of awareness?', answer: 'Yes' },
      { id: 'q11', text: 'Should unauthorised people be allowed into the vehicle?', answer: 'No' },
    ],
  },
  {
    category: 'Travel & special duty',
    topic: 'Driver security duties',
    questions: [
      { id: 'q01', text: 'Should the vehicle be checked before movement?', answer: 'Yes' },
      { id: 'q02', text: 'Is using a mobile while driving acceptable?', answer: 'No' },
      { id: 'q03', text: 'Must doors be locked while moving as per SOP?', answer: 'Yes' },
      { id: 'q04', text: 'Are unauthorised passengers allowed?', answer: 'No' },
      { id: 'q05', text: 'Should unknown parcels for strangers be carried?', answer: 'No' },
      { id: 'q06', text: 'Must mechanical issues be reported early?', answer: 'Yes' },
      { id: 'q07', text: 'Are vehicle documents part of pre-move checks?', answer: 'Yes' },
      { id: 'q08', text: 'Should fuel / tyre issues be ignored until the trip fails?', answer: 'No' },
      { id: 'q09', text: 'Is driver–security coordination important?', answer: 'Yes' },
      { id: 'q10', text: 'Can unsafe driving create risk for the traveller?', answer: 'Yes' },
      { id: 'q11', text: 'Should SOP for locks and checks be followed every trip?', answer: 'Yes' },
    ],
  },
  {
    category: 'Travel & special duty',
    topic: 'STF / quick response support',
    questions: [
      { id: 'q01', text: 'Should site guards support STF with clear location information?', answer: 'Yes' },
      { id: 'q02', text: 'Is doing hero stunts alone better than following command?', answer: 'No' },
      { id: 'q03', text: 'Must access be cleared for the response team?', answer: 'Yes' },
      { id: 'q04', text: 'Should there be one channel of command during response?', answer: 'Yes' },
      { id: 'q05', text: 'Is crowding the incident with all guards helpful?', answer: 'No' },
      { id: 'q06', text: 'After action, should factual support notes be written?', answer: 'Yes' },
      { id: 'q07', text: 'Should guards know their role: guide, cordon, information?', answer: 'Yes' },
      { id: 'q08', text: 'Must team leader instructions be followed?', answer: 'Yes' },
      { id: 'q09', text: 'Can wrong information delay response?', answer: 'Yes' },
      { id: 'q10', text: 'Should trainers explain when STF is called?', answer: 'Yes' },
      { id: 'q11', text: 'Is ignoring arriving STF vehicles at the gate acceptable?', answer: 'No' },
    ],
  },
  {
    category: 'Travel & special duty',
    topic: 'Unusual person / vehicle reporting',
    questions: [
      { id: 'q01', text: 'Should unusual loitering be reported?', answer: 'Yes' },
      { id: 'q02', text: 'Must time, clothing and vehicle number be noted when possible?', answer: 'Yes' },
      { id: 'q03', text: 'Is chasing alone into a dark deserted area recommended?', answer: 'No' },
      { id: 'q04', text: 'Should Control / supervisor be informed quickly?', answer: 'Yes' },
      { id: 'q05', text: 'Can repeated drive-bys be a useful observation?', answer: 'Yes' },
      { id: 'q06', text: 'Is “see something, say something” part of duty?', answer: 'Yes' },
      { id: 'q07', text: 'Should a 4-line unusual activity report be practised?', answer: 'Yes' },
      { id: 'q08', text: 'Must direction and behaviour be included when known?', answer: 'Yes' },
      { id: 'q09', text: 'Is confronting a dangerous person alone always required?', answer: 'No' },
      { id: 'q10', text: 'Can good reporting prevent a larger incident?', answer: 'Yes' },
      { id: 'q11', text: 'Should photography of gates by strangers be ignored always?', answer: 'No' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Bank & ATM security',
    questions: [
      { id: 'q01', text: 'Should cash movement timings be discussed in public?', answer: 'No' },
      { id: 'q02', text: 'Must opening / closing drills be known where applicable?', answer: 'Yes' },
      { id: 'q03', text: 'Should loitering near ATM be watched?', answer: 'Yes' },
      { id: 'q04', text: 'Is posting vault / ATM room photos on social media allowed?', answer: 'No' },
      { id: 'q05', text: 'Should shoulder surfing and skimming risks be understood?', answer: 'Yes' },
      { id: 'q06', text: 'Must alarm / police escalation follow bank SOP?', answer: 'Yes' },
      { id: 'q07', text: 'Should customer cards / bags be held by the guard casually?', answer: 'No' },
      { id: 'q08', text: 'Is dual control important where the bank requires it?', answer: 'Yes' },
      { id: 'q09', text: 'Can weak ATM vigilance create client loss?', answer: 'Yes' },
      { id: 'q10', text: 'Should night ATM checks include unusual devices nearby?', answer: 'Yes' },
      { id: 'q11', text: 'Is bank security only about customer service and never access control?', answer: 'No' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Pharma industry security',
    questions: [
      { id: 'q01', text: 'Should restricted / clean areas be respected?', answer: 'Yes' },
      { id: 'q02', text: 'Is unauthorised photography in process areas allowed?', answer: 'No' },
      { id: 'q03', text: 'Must scrap and material outward be strictly controlled?', answer: 'Yes' },
      { id: 'q04', text: 'Should spills or odd smells that may be unsafe be reported?', answer: 'Yes' },
      { id: 'q05', text: 'Can a guard enter production without authorisation?', answer: 'No' },
      { id: 'q06', text: 'Are gowning / badge zone rules important where applicable?', answer: 'Yes' },
      { id: 'q07', text: 'Does weak material control create quality and theft risk?', answer: 'Yes' },
      { id: 'q08', text: 'Should visitor control be strict in pharma sites?', answer: 'Yes' },
      { id: 'q09', text: 'Is ignoring induction rules before entry acceptable?', answer: 'No' },
      { id: 'q10', text: 'Must trainers align teaching with site badge zones?', answer: 'Yes' },
      { id: 'q11', text: 'Can scrap outward without checks be a high risk?', answer: 'Yes' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Automobile industry security',
    questions: [
      { id: 'q01', text: 'Is a gate pass required for parts / tools as per SOP?', answer: 'Yes' },
      { id: 'q02', text: 'Should parking yards and unfinished vehicles be watched?', answer: 'Yes' },
      { id: 'q03', text: 'Can personal vehicles enter restricted yards without pass?', answer: 'No' },
      { id: 'q04', text: 'Must contractor tools in/out be accounted for?', answer: 'Yes' },
      { id: 'q05', text: 'Are fire risks higher near welding / paint shops?', answer: 'Yes' },
      { id: 'q06', text: 'Should extinguisher points in plant areas be known?', answer: 'Yes' },
      { id: 'q07', text: 'Is parts theft a real risk in automobile sites?', answer: 'Yes' },
      { id: 'q08', text: 'Must loaded parts vehicles have proper documents?', answer: 'Yes' },
      { id: 'q09', text: 'Should unauthorised material exit be stopped?', answer: 'Yes' },
      { id: 'q10', text: 'Is ignoring yard patrol acceptable on night shift?', answer: 'No' },
      { id: 'q11', text: 'Can weak contractor control increase losses?', answer: 'Yes' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'IT / office campus security',
    questions: [
      { id: 'q01', text: 'Is tailgating at flap barriers a major risk?', answer: 'Yes' },
      { id: 'q02', text: 'Should access cards be shared with colleagues?', answer: 'No' },
      { id: 'q03', text: 'Must lost access cards be reported immediately?', answer: 'Yes' },
      { id: 'q04', text: 'Is visitor escort culture important in IT campuses?', answer: 'Yes' },
      { id: 'q05', text: 'Should people photograph badges / screens without permission?', answer: 'No' },
      { id: 'q06', text: 'Can a polite employee still be stopped for tailgating?', answer: 'Yes' },
      { id: 'q07', text: 'Must meeting-floor visitor rules be followed?', answer: 'Yes' },
      { id: 'q08', text: 'Is piggybacking on another’s card entry acceptable?', answer: 'No' },
      { id: 'q09', text: 'Should trainers role-play stopping tailgating politely?', answer: 'Yes' },
      { id: 'q10', text: 'Does weak access control risk data and asset security?', answer: 'Yes' },
      { id: 'q11', text: 'Can “I forgot my card, let me in” skip all process every day?', answer: 'No' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Hotel security',
    questions: [
      { id: 'q01', text: 'Should guest room numbers be given to strangers?', answer: 'No' },
      { id: 'q02', text: 'Is lobby vigilance for unattended bags important?', answer: 'Yes' },
      { id: 'q03', text: 'Must hospitality and firm security work together?', answer: 'Yes' },
      { id: 'q04', text: 'Should guest privacy be protected?', answer: 'Yes' },
      { id: 'q05', text: 'Can a guard enter guest rooms alone against hotel SOP?', answer: 'No' },
      { id: 'q06', text: 'Is coordination with front office needed for VIP / incidents?', answer: 'Yes' },
      { id: 'q07', text: 'Should loitering in lobby be observed?', answer: 'Yes' },
      { id: 'q08', text: 'Does disclosing guest details create risk?', answer: 'Yes' },
      { id: 'q09', text: 'Must unattended luggage be handled as per SOP?', answer: 'Yes' },
      { id: 'q10', text: 'Is guest dignity part of hotel security behaviour?', answer: 'Yes' },
      { id: 'q11', text: 'Should hotel security ignore front-office process for friends?', answer: 'No' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Hospital security',
    questions: [
      { id: 'q01', text: 'Must emergency pathways stay clear for ambulance / trolley?', answer: 'Yes' },
      { id: 'q02', text: 'Should patient information be shared publicly?', answer: 'No' },
      { id: 'q03', text: 'Is firm politeness needed with attendants?', answer: 'Yes' },
      { id: 'q04', text: 'Can parking arguments block the ER entrance?', answer: 'No' },
      { id: 'q05', text: 'Should theft of equipment be watched for?', answer: 'Yes' },
      { id: 'q06', text: 'Must Code procedures be supported as per hospital training?', answer: 'Yes' },
      { id: 'q07', text: 'Is ambulance arrival a priority moment for access?', answer: 'Yes' },
      { id: 'q08', text: 'Should ward disputes be escalated as per SOP?', answer: 'Yes' },
      { id: 'q09', text: 'Can blocked emergency access cost lives?', answer: 'Yes' },
      { id: 'q10', text: 'Is hospital security only about visitor passes and never pathways?', answer: 'No' },
      { id: 'q11', text: 'Should trainers stress clear ER access?', answer: 'Yes' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'School / college campus security',
    questions: [
      { id: 'q01', text: 'Must unknown adults follow visitor process before entry?', answer: 'Yes' },
      { id: 'q02', text: 'Can a child be released to an unverified “uncle”?', answer: 'No' },
      { id: 'q03', text: 'Should pickup rules and authorised guardian process be known?', answer: 'Yes' },
      { id: 'q04', text: 'Is bus bay discipline important near the gate?', answer: 'Yes' },
      { id: 'q05', text: 'Should rash driving near school gates be controlled?', answer: 'Yes' },
      { id: 'q06', text: 'Must stranger-danger observations be reported to admin / HOD?', answer: 'Yes' },
      { id: 'q07', text: 'Is gentle and alert behaviour needed with children?', answer: 'Yes' },
      { id: 'q08', text: 'Can weak gate control put students at risk?', answer: 'Yes' },
      { id: 'q09', text: 'Should trainers stress child safety above convenience?', answer: 'Yes' },
      { id: 'q10', text: 'Is visitor screening optional during busy school hours?', answer: 'No' },
      { id: 'q11', text: 'Must campus security take student safety as top priority?', answer: 'Yes' },
    ],
  },
  {
    category: 'Industry / site',
    topic: 'Plant / infrastructure security (cement, fertiliser, etc.)',
    questions: [
      { id: 'q01', text: 'Should PPE rules at plant gates be respected?', answer: 'Yes' },
      { id: 'q02', text: 'Is long perimeter patrol important at plants?', answer: 'Yes' },
      { id: 'q03', text: 'Can a guard enter process areas without escort and PPE?', answer: 'No' },
      { id: 'q04', text: 'Must truck / material movements be checked carefully?', answer: 'Yes' },
      { id: 'q05', text: 'Should lighting gaps on the perimeter be reported?', answer: 'Yes' },
      { id: 'q06', text: 'Are contractor induction rules important before entry?', answer: 'Yes' },
      { id: 'q07', text: 'Is weighbridge / gate coordination useful where available?', answer: 'Yes' },
      { id: 'q08', text: 'Can material theft be a major plant risk?', answer: 'Yes' },
      { id: 'q09', text: 'Should under-loading / over-loading tricks be watched?', answer: 'Yes' },
      { id: 'q10', text: 'Is ignoring PPE zones acceptable for “quick work”?', answer: 'No' },
      { id: 'q11', text: 'Must trainers mention plant-specific hazards in OJT?', answer: 'Yes' },
    ],
  },
  {
    category: 'Turnout & behaviour',
    topic: 'ID card Importance',
    questions: [
      { id: 'q01', text: 'Must a guard wear the Agile ID card on duty?', answer: 'Yes' },
      { id: 'q02', text: 'Should the ID photo be visible on the outer garment?', answer: 'Yes' },
      { id: 'q03', text: 'Is keeping ID hidden in the pocket correct practice?', answer: 'No' },
      { id: 'q04', text: 'Should visitor / contractor ID be checked as per site rule?', answer: 'Yes' },
      { id: 'q05', text: 'Can an expired ID be accepted without escalation?', answer: 'No' },
      { id: 'q06', text: 'Does a valid ID prove the guard is authorised on duty?', answer: 'Yes' },
      { id: 'q07', text: 'Should borrowed IDs be stopped and escalated?', answer: 'Yes' },
      { id: 'q08', text: 'Is ID important during audits and incidents?', answer: 'Yes' },
      { id: 'q09', text: 'Can “I forgot my ID” be ignored every day without supervisor approval?', answer: 'No' },
      { id: 'q10', text: 'Should trainers practise reading name and validity on the ID?', answer: 'Yes' },
      { id: 'q11', text: 'Does ID protect the guard, client and company?', answer: 'Yes' },
    ],
  },
]

export function questionBanksGrouped(): { category: string; banks: OjtTopicQuestionBank[] }[] {
  const order: string[] = []
  const map = new Map<string, OjtTopicQuestionBank[]>()
  for (const b of OJT_TOPIC_QUESTION_BANKS) {
    if (!map.has(b.category)) {
      map.set(b.category, [])
      order.push(b.category)
    }
    map.get(b.category)!.push(b)
  }
  return order.map((category) => ({ category, banks: map.get(category)! }))
}

function normTopic(s: string): string {
  return String(s || '')
    .trim()
    .toLowerCase()
    .replace(/^\d+\.\s*/, '')
    .replace(/\s+/g, ' ')
}

export function findTopicQuestionBank(topic: string): OjtTopicQuestionBank | null {
  const t = normTopic(topic)
  if (!t) return null
  const exact = OJT_TOPIC_QUESTION_BANKS.find((b) => normTopic(b.topic) === t)
  if (exact) return exact
  const includes = OJT_TOPIC_QUESTION_BANKS.find((b) => {
    const n = normTopic(b.topic)
    return n.includes(t) || t.includes(n)
  })
  return includes || null
}

/** Safe JSON for embedding in page script. */
export function questionBanksJsonForPage(): string {
  return JSON.stringify(questionBanksGrouped()).replace(/</g, '\\u003c')
}
