import { QUIZ, STARTER_QUIZ_BANK } from './config.js'
import { redisCommand } from './store.js'
import type { QuizEntry, QuizQuestion, QuizWinner, PendingQuizWinner } from './types.js'

/**
 * Security Question of the Day engine.
 * - A question bank (added by managers and/or generated by AI)
 * - One question per day, no repeat for 60 days
 * - Weekly prize-draw entries and a published winners board
 * All stored in Upstash Redis so everything is remembered permanently.
 */

const BANK_KEY = 'pulse:quiz:bank'
const USED_KEY = 'pulse:quiz:used'
const WINNERS_KEY = 'pulse:quiz:winners'
const PENDING_WINNER_KEY = 'pulse:quiz:pending-winner'
const NO_REPEAT_DAYS = 60
const OPTION_KEYS = ['A', 'B', 'C', 'D']

const IST_OFFSET_MIN = 5 * 60 + 30
function istNow(): Date {
  const utcMs = Date.now() + new Date().getTimezoneOffset() * 60000
  return new Date(utcMs + IST_OFFSET_MIN * 60000)
}
function istDateKey(): string {
  const d = istNow()
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}
/** ISO-ish week key like 2026-W27, in IST. Optional date override. */
export function weekKey(base?: Date): string {
  const d = base ?? istNow()
  const target = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()))
  const dayNr = (target.getUTCDay() + 6) % 7
  target.setUTCDate(target.getUTCDate() - dayNr + 3)
  const firstThursday = new Date(Date.UTC(target.getUTCFullYear(), 0, 4))
  const week =
    1 +
    Math.round(
      ((target.getTime() - firstThursday.getTime()) / 86400000 - 3 + ((firstThursday.getUTCDay() + 6) % 7)) / 7,
    )
  return `${target.getUTCFullYear()}-W${String(week).padStart(2, '0')}`
}

function fallbackQuestion(): QuizQuestion {
  return {
    id: 'default',
    type: 'text',
    question: QUIZ.question,
    imageUrl: '',
    options: QUIZ.options,
    correctKey: QUIZ.correctKey,
    explanation: QUIZ.explanation,
  }
}

export async function getBank(): Promise<QuizQuestion[]> {
  const data = await redisCommand(['GET', BANK_KEY])
  if (data?.result && typeof data.result === 'string') {
    try {
      const arr = JSON.parse(data.result)
      if (Array.isArray(arr) && arr.length > 0) return arr as QuizQuestion[]
    } catch {
      /* ignore */
    }
  }
  // Nothing saved yet — use the built-in Security & Fire-Safety bank.
  return STARTER_QUIZ_BANK
}

export async function saveBank(bank: QuizQuestion[]): Promise<boolean> {
  const result = await redisCommand(['SET', BANK_KEY, JSON.stringify(bank)])
  return result?.result === 'OK'
}

async function getUsedMap(): Promise<Record<string, string>> {
  const data = await redisCommand(['GET', USED_KEY])
  if (data?.result && typeof data.result === 'string') {
    try {
      return JSON.parse(data.result) as Record<string, string>
    } catch {
      /* ignore */
    }
  }
  return {}
}

export async function getQuestionById(id: string): Promise<QuizQuestion | null> {
  if (id === 'default') return fallbackQuestion()
  const bank = await getBank()
  return bank.find((q) => q.id === id) ?? null
}

/** Pick (and remember) today's question, respecting the 60-day no-repeat rule. */
export async function getTodayQuestion(): Promise<QuizQuestion> {
  const dkey = istDateKey()
  const todayKey = `pulse:quiz:today:${dkey}`

  const existing = await redisCommand(['GET', todayKey])
  const bank = await getBank()
  if (existing?.result && typeof existing.result === 'string') {
    const q = bank.find((b) => b.id === existing.result)
    if (q) return q
    if (existing.result === 'default') return fallbackQuestion()
  }

  if (bank.length === 0) return fallbackQuestion()

  const used = await getUsedMap()
  const now = Date.now()
  const eligible = bank.filter((b) => {
    const u = used[b.id]
    return !u || now - new Date(u).getTime() > NO_REPEAT_DAYS * 86400000
  })
  const pool = eligible.length > 0 ? eligible : bank
  const pick = pool[Math.floor(Math.random() * pool.length)]

  await redisCommand(['SET', todayKey, pick.id, 'EX', 172800])
  used[pick.id] = new Date().toISOString()
  await redisCommand(['SET', USED_KEY, JSON.stringify(used)])
  return pick
}

/* ---------- weekly prize-draw entries ---------- */

export async function addEntry(name: string, mobile: string, guardId?: string): Promise<boolean> {
  const gid = guardId ? guardId.replace(/\D/g, '').slice(0, 20) : ''
  const entry: QuizEntry = {
    name: name.slice(0, 80),
    mobile: mobile.replace(/\D/g, '').slice(0, 15),
    date: new Date().toISOString(),
    ...(gid ? { guardId: gid } : {}),
  }
  const result = await redisCommand(['RPUSH', `pulse:quiz:entries:${weekKey()}`, JSON.stringify(entry)])
  return typeof result?.result === 'number'
}

export async function getEntries(week: string): Promise<QuizEntry[]> {
  const data = await redisCommand(['LRANGE', `pulse:quiz:entries:${week}`, 0, -1])
  const arr = Array.isArray(data?.result) ? (data!.result as string[]) : []
  return arr
    .map((s) => {
      try {
        return JSON.parse(s) as QuizEntry
      } catch {
        return null
      }
    })
    .filter((e): e is QuizEntry => e !== null)
}

/* ---------- winners board ---------- */

export async function getWinners(): Promise<QuizWinner[]> {
  const data = await redisCommand(['LRANGE', WINNERS_KEY, 0, 9])
  const arr = Array.isArray(data?.result) ? (data!.result as string[]) : []
  return arr
    .map((s) => {
      try {
        return JSON.parse(s) as QuizWinner
      } catch {
        return null
      }
    })
    .filter((w): w is QuizWinner => w !== null)
}

export async function addWinner(winner: QuizWinner): Promise<boolean> {
  const result = await redisCommand(['LPUSH', WINNERS_KEY, JSON.stringify(winner)])
  return typeof result?.result === 'number'
}

export async function winnerPublishedForWeek(week: string): Promise<boolean> {
  const winners = await getWinners()
  return winners.some((w) => w.weekKey === week)
}

export async function getPendingWinner(): Promise<PendingQuizWinner | null> {
  const data = await redisCommand(['GET', PENDING_WINNER_KEY])
  if (data?.result && typeof data.result === 'string') {
    try {
      return JSON.parse(data.result) as PendingQuizWinner
    } catch {
      return null
    }
  }
  return null
}

export async function setPendingWinner(p: PendingQuizWinner): Promise<boolean> {
  const result = await redisCommand(['SET', PENDING_WINNER_KEY, JSON.stringify(p), 'EX', 604800])
  return result?.result === 'OK'
}

export async function clearPendingWinner(): Promise<void> {
  await redisCommand(['DEL', PENDING_WINNER_KEY])
}

/** Week to draw on Sunday morning (Mon–Sat entries of the week just ending). */
export function drawTargetWeekKey(): string {
  const d = istNow()
  const dow = d.getUTCDay()
  if (dow === 0) {
    const sat = new Date(d.getTime() - 86400000)
    return weekKey(sat)
  }
  return weekKey(d)
}

/** Pick a random entrant without publishing (for approval flow). */
export async function pickWinnerCandidate(week: string): Promise<PendingQuizWinner | null> {
  const entries = await getEntries(week)
  if (entries.length === 0) return null
  const pick = entries[Math.floor(Math.random() * entries.length)]
  const mobile = pick.mobile.replace(/\D/g, '').slice(0, 15)
  return {
    weekKey: week,
    name: pick.name || 'Participant',
    mobile,
    mobileLast4: mobile.slice(-4),
    entryCount: entries.length,
    ts: Date.now(),
    ...(pick.guardId ? { guardId: pick.guardId } : {}),
  }
}

/** Publish "no winner" for a week (automatic — no Director approval). */
export async function publishNoWinner(week: string): Promise<QuizWinner> {
  const record: QuizWinner = {
    weekKey: week,
    name: 'No winner this week',
    mobileLast4: '',
    date: new Date().toISOString(),
    noWinner: true,
  }
  await addWinner(record)
  return record
}

/** Prepare weekly draw — stores pending winner for Director approval. */
export async function prepareWeeklyDraw(week: string): Promise<
  | { ok: true; pending: PendingQuizWinner }
  | { ok: false; reason: 'no-entries' | 'already-published' | 'already-pending' }
> {
  if (await winnerPublishedForWeek(week)) return { ok: false, reason: 'already-published' }
  if (await getPendingWinner()) return { ok: false, reason: 'already-pending' }
  const candidate = await pickWinnerCandidate(week)
  if (!candidate) return { ok: false, reason: 'no-entries' }
  await setPendingWinner(candidate)
  return { ok: true, pending: candidate }
}

/** Publish pending winner to the bulletin winners board. */
export async function publishPendingWinner(pending: PendingQuizWinner): Promise<QuizWinner> {
  const winner: QuizWinner = {
    weekKey: pending.weekKey,
    name: pending.name,
    mobileLast4: pending.mobileLast4,
    date: new Date().toISOString(),
  }
  await addWinner(winner)
  await clearPendingWinner()
  return winner
}

/** Pick a random winner from a given week's correct entries and publish it. */
export async function drawWinner(week: string): Promise<QuizWinner | null> {
  const candidate = await pickWinnerCandidate(week)
  if (!candidate) return null
  const winner: QuizWinner = {
    weekKey: candidate.weekKey,
    name: candidate.name,
    mobileLast4: candidate.mobileLast4,
    date: new Date().toISOString(),
  }
  await addWinner(winner)
  return winner
}

/* ---------- AI question generation ---------- */

function keyId(): string {
  return `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 7)}`
}

function extractJsonArray(text: string): any[] {
  const cleaned = text.replace(/```json/gi, '').replace(/```/g, '').trim()
  const start = cleaned.indexOf('[')
  const end = cleaned.lastIndexOf(']')
  if (start === -1 || end === -1) return []
  try {
    const arr = JSON.parse(cleaned.slice(start, end + 1))
    return Array.isArray(arr) ? arr : []
  } catch {
    return []
  }
}

function toQuestions(raw: any[]): QuizQuestion[] {
  const out: QuizQuestion[] = []
  for (const r of raw) {
    const q = String(r?.question ?? '').trim()
    const opts = Array.isArray(r?.options) ? r.options.map((o: unknown) => String(o ?? '').trim()) : []
    let idx = Number(r?.correctIndex)
    if (!q || opts.length < 2) continue
    if (isNaN(idx) || idx < 0 || idx >= opts.length) idx = 0
    const options = opts.slice(0, 4).map((text: string, i: number) => ({ key: OPTION_KEYS[i], text }))
    out.push({
      id: keyId(),
      type: 'text',
      question: q,
      imageUrl: '',
      options,
      correctKey: OPTION_KEYS[Math.min(idx, options.length - 1)],
      explanation: String(r?.explanation ?? '').trim(),
    })
  }
  return out
}

const AI_PROMPT = (count: number) =>
  `Generate ${count} multiple-choice quiz questions to train private security guards in India on security duties AND fire-safety/first-aid awareness. ` +
  `Keep them clear and practical. Each must have exactly 4 options, one correct answer, and a one-sentence explanation. ` +
  `Return ONLY a JSON array, no other text, in this exact form: ` +
  `[{"question":"...","options":["...","...","...","..."],"correctIndex":0,"explanation":"..."}]`

async function fetchJson(url: string, init: RequestInit): Promise<any | null> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 25000)
  try {
    const res = await fetch(url, { ...init, signal: controller.signal })
    if (!res.ok) return null
    return await res.json()
  } catch {
    return null
  } finally {
    clearTimeout(timer)
  }
}

export async function generateQuestions(count: number): Promise<{ questions: QuizQuestion[]; error?: string }> {
  const n = Math.max(1, Math.min(10, count || 5))
  const perplexity = process.env.PERPLEXITY_API_KEY?.trim()
  const openai = process.env.OPENAI_API_KEY?.trim()

  if (perplexity) {
    const data = await fetchJson('https://api.perplexity.ai/chat/completions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${perplexity}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'sonar',
        messages: [
          { role: 'system', content: 'You are a security-training question writer. Reply with JSON only.' },
          { role: 'user', content: AI_PROMPT(n) },
        ],
        temperature: 0.5,
        max_tokens: 1500,
      }),
    })
    const text = data?.choices?.[0]?.message?.content
    if (typeof text === 'string') {
      const qs = toQuestions(extractJsonArray(text))
      if (qs.length > 0) return { questions: qs }
    }
  }

  if (openai) {
    const data = await fetchJson('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${openai}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'You are a security-training question writer. Reply with JSON only.' },
          { role: 'user', content: AI_PROMPT(n) },
        ],
        temperature: 0.5,
      }),
    })
    const text = data?.choices?.[0]?.message?.content
    if (typeof text === 'string') {
      const qs = toQuestions(extractJsonArray(text))
      if (qs.length > 0) return { questions: qs }
    }
  }

  if (!perplexity && !openai) {
    return { questions: [], error: 'No AI key set. Add PERPLEXITY_API_KEY (or OPENAI_API_KEY) in Vercel.' }
  }
  return { questions: [], error: 'AI did not return questions. Please try again.' }
}
