/**
 * HDFC Bank Site Security Assessment (SSA) — 15 headed sections (Director 17 Aug 2026).
 * Prefer selects / Yes-No to cut manual typing; surroundings analysis included.
 */

export const HDFC_FORM_KEYS = [
  // 1. Location and Identification
  'clientPickHint',
  'branchName',
  'solId',
  'fullAddress',
  'locationCategory',
  'geoLandmark',
  'surroundLeft',
  'surroundRight',
  'surroundFront',
  'surroundBack',
  'nearestFireStation',
  'nearestFireStationKm',
  'nearestPoliceStation',
  'nearestPoliceStationKm',
  'wineShopNearby',
  'barsNearby',
  'shops24x7Nearby',
  'busStandNearby',
  'railwayStationNearby',
  'politicalPartyOfficeNearby',
  'airportNearby',
  'publicMovement24x7',
  'remoteAtNight',
  'locationRiskNote',
  // 2. Basic Information
  'managerName',
  'contactNumber',
  'contactEmail',
  'surveyDate',
  'surveyedByPick',
  'surveyedBy',
  'branchCategory',
  'workingHours',
  'holidayOpenPermission',
  'faKnowsProcedure',
  // 3. Deployment verification
  'sanctionedGuards',
  'dayShiftStart',
  'afternoonShiftStart',
  'eveningShiftStart',
  'faOnDuty',
  'deploymentMatch',
  'deploymentGapNotes',
  'facilityAttendantsJson',
  // legacy keys kept for older saved rows
  'firstFloorLeft',
  'firstFloorRight',
  'firstFloorFront',
  'firstFloorBack',
  'actualGuardsDay',
  'actualGuardsNight',
  'asoPresent',
  'lsgPresent',
  'sgPresent',
  // 4. Registers and Compliance log
  'attendanceRegister',
  'hotoRegister',
  'occurrenceRegister',
  'breakRegister',
  'generatorRegister',
  'cashLoadingRegister',
  'bankOpenCloseRegister',
  'complianceFile',
  'holidayRegisterKeepPlace',
  'faDocPvc',
  'faDocMedical',
  'faDocDeploymentOrder',
  'complianceGapNotes',
  // legacy register keys (older saved rows)
  'visitorRegister',
  'keyRegister',
  'cashVaultRegister',
  'atmRegister',
  'patrolRegister',
  // 5. Bank Physical Security — doors/windows/holiday
  'mainEntranceDoor',
  'mainEntranceProcedure',
  'shutterCondition',
  'shutterOpenCloseProcedure',
  'windowsSecure',
  'windowOpenCloseProcedure',
  'entryPointsToBank',
  'openPosition',
  'backYardDoor',
  'damagedWindows',
  'closingBankChecklist',
  'whoLocksBank',
  'whoSealsKeys',
  'holidayOpeningPermission',
  'holidayOpenCloseProcedure',
  'physicalSecurityNotes',
  // legacy physical (older saved rows)
  'fireExtCount',
  'fireExtValidityChecked',
  'fireExtExpired',
  'strongRoomDoorClass',
  'strongRoomVentilator',
  'emergencyExit',
  // 6. ATM & Lobby
  'atmSite',
  'atmCount',
  'atmShiftCount',
  'atmKeySets',
  'atmOpenWiring',
  'atmOpenPowerSocket',
  'atmOpenConnection',
  'faBelongingsInAtm',
  'atmDrawerContents',
  'atmLobbyClean',
  'unauthStickers',
  'atmVisibleFromRoad',
  'surroundNightLighting',
  'patrolBeforeTakeover',
  'atmAccessCount',
  'canAccessBankFromAtm',
  'atmCctv',
  'atmGuarding',
  'atmLobbyAccess',
  'atmLobbyLighting',
  'atmLobbyNotes',
  // 7. Generator & Utility
  'generatorPresent',
  'generatorLocation',
  'generatorVisibleFromAtm',
  'generatorCctvCoverage',
  'generatorAreaLuminated',
  'generatorRegisterMaintained',
  'generatorBattery',
  'generatorLockIntact',
  'generatorWorking',
  'generatorStartedBy',
  'generatorDieselBy',
  'generatorFuel',
  'upsPresent',
  'upsBackupHours',
  'utilityNotes',
  // 8. Perimeter surveillance & Patrolling
  'perimeterFence',
  'perimeterLighting',
  'cctvPerimeter',
  'patrolFrequency',
  'patrolRouteOk',
  'outdoorAcUnit',
  'outdoorAcLighting',
  'outdoorAcCctv',
  'patrolNotes',
  // 9. Fire safety (ATM & Branch)
  'feAtmCount',
  'feAtmCo2',
  'feAtmDcp',
  'feAtmFoam',
  'feAtmMixed',
  'feBankCount',
  'feBankCo2',
  'feBankDcp',
  'feBankFoam',
  'feBankMixed',
  'cookingHeatingAvailable',
  'microwavePresent',
  'recentFireAudit',
  'recentFireDrill',
  'smokeDetectors',
  'fireAlarm',
  'atmFireSafety',
  'branchFireSafety',
  'fireSafetyNotes',
  // legacy fire (older saved rows)
  'fireExtinguisherType',
  'fireExtinguisherQty',
  'fireExtinguisherRefillDue',
  'fireDrillDone',
  // 10. Emergency communication & reporting
  'routerInstalled',
  'panicSwitchAtm',
  'agileControlNumber',
  'faKnowledgeAgileMobileAlarm',
  'emergencyContactDisplayedFa',
  'escalationKnownFa',
  'emergencyContactBank',
  'emergencyContactPolice',
  'emergencyContactFire',
  'emergencyNotes',
  // legacy emergency (older saved rows)
  'panicSwitchCount',
  'panicSwitchStatus',
  'burglarAlarm',
  'escalationKnown',
  // 11. Electronic Security Systems
  'cctvAtmCount',
  'cctvBankCount',
  'localDvrLocation',
  'cctvCableOpen',
  'cctvCameraCount',
  'dvrNvrChannels',
  'dvrNvrHdd',
  'recordingBackupDays',
  'cctvCoverageOk',
  'electronicNotes',
  // Shared remarks / sign-off (used on final + reports)
  'generalObservations',
  'hdfcRecommendations',
  'surveyorSign',
  'branchRepSign',
  /** Set when Risk Analyst taps Review the report on page 15 */
  'page15Reviewed',
] as const

export type HdfcFormKey = (typeof HDFC_FORM_KEYS)[number]

export function emptyHdfcForm(): Record<string, string> {
  const out: Record<string, string> = {}
  for (const k of HDFC_FORM_KEYS) out[k] = ''
  return out
}

export function normalizeHdfcForm(raw: unknown): Record<string, string> {
  const src = raw && typeof raw === 'object' ? (raw as Record<string, unknown>) : {}
  const out = emptyHdfcForm()
  for (const k of HDFC_FORM_KEYS) {
    out[k] = String(src[k] ?? '').slice(0, 4000)
  }
  // Legacy key aliases from earlier short form
  if (!out.fullAddress && src.address) out.fullAddress = String(src.address).slice(0, 4000)
  return out
}

export const HDFC_YN = ['Yes', 'No', 'NA'] as const
export const HDFC_STATUS = ['Working', 'Not Working', 'Needs Repair', 'NA'] as const
export const HDFC_LOC_CAT = ['Urban', 'Semi-Urban', 'Rural'] as const
export const HDFC_MOVEMENT = ['High 24x7', 'Moderate', 'Low / Quiet at night', 'Remote / Isolated at night'] as const

/** Tab id → short label (shown under HDFC survey). */
export const HDFC_TABS: { id: string; label: string }[] = [
  { id: 'h1', label: '1. Location & Identification' },
  { id: 'h2', label: '2. Basic Information' },
  { id: 'h3', label: '3. Deployment verification' },
  { id: 'h4', label: '4. Registers & Compliance' },
  { id: 'h5', label: '5. Bank Physical security' },
  { id: 'h6', label: '6. ATM & Lobby' },
  { id: 'h7', label: '7. Generator & Utility' },
  { id: 'h8', label: '8. Perimeter & Patrolling' },
  { id: 'h9', label: '9. Fire safety' },
  { id: 'h10', label: '10. Emergency communication' },
  { id: 'h11', label: '11. Electronic Security' },
  { id: 'checklist', label: '12. Risk check list' },
  { id: 'report', label: '13. Professional assessment' },
  { id: 'photos', label: '14. Site Photos & Documents' },
  { id: 'final', label: '15. Final Report with suggestions' },
]

export const HDFC_FORM_LABELS: Record<string, string> = {
  branchName: 'Branch Name',
  solId: 'SOL ID',
  fullAddress: 'Full Address',
  locationCategory: 'Location / Category',
  geoLandmark: 'Landmark',
  surroundLeft: 'Ground — Left',
  surroundRight: 'Ground — Right',
  surroundFront: 'Ground — Front',
  surroundBack: 'Ground — Back',
  firstFloorLeft: 'First floor — Left',
  firstFloorRight: 'First floor — Right',
  firstFloorFront: 'First floor — Front',
  firstFloorBack: 'First floor — Back',
  nearestFireStation: 'Nearest Fire Station',
  nearestFireStationKm: 'Fire Station distance (km)',
  nearestPoliceStation: 'Nearest Police Station',
  nearestPoliceStationKm: 'Police Station distance (km)',
  wineShopNearby: 'Wine shop nearby',
  barsNearby: 'Bars nearby',
  shops24x7Nearby: '24×7 shops nearby',
  busStandNearby: 'Bus stand nearby',
  railwayStationNearby: 'Railway station nearby',
  politicalPartyOfficeNearby: 'Political Party office nearby',
  airportNearby: 'Airport nearby',
  publicMovement24x7: '24×7 public movement',
  remoteAtNight: 'Remote / isolated at night',
  locationRiskNote: 'Location risk note',
  managerName: 'Name of the Manager',
  contactNumber: 'Contact Number',
  contactEmail: 'Email',
  surveyDate: 'Date of Survey',
  surveyedByPick: 'Surveyed By (operations team)',
  surveyedBy: 'Surveyed By (name)',
  branchCategory: 'Branch category',
  workingHours: 'Working hours',
  holidayOpenPermission: 'Holiday opening is on the file',
  faKnowsProcedure: 'Whether FA knows the procedure',
  sanctionedGuards: 'Sanctioned strength',
  dayShiftStart: 'Actual Day shift start time',
  afternoonShiftStart: 'Actual afternoon shift start time',
  eveningShiftStart: 'Actual evening shift start time',
  faOnDuty: 'FA on duty',
  deploymentMatch: 'Deployment matches sanction',
  deploymentGapNotes: 'Deployment gap notes',
  facilityAttendantsJson: 'Facility Attendants',
  attendanceRegister: 'Attendance Register',
  hotoRegister: 'HOTO',
  occurrenceRegister: 'Occurrence Register',
  breakRegister: 'Break Register',
  generatorRegister: 'Generator Register',
  cashLoadingRegister: 'Cash Loading register',
  bankOpenCloseRegister: 'Bank Opening and closing Register',
  complianceFile: 'Compliance File',
  holidayRegisterKeepPlace: 'During Bank Holidays — where will FA keep Register & files',
  faDocPvc: 'Document for all FAs — PVC',
  faDocMedical: 'Document for all FAs — Medical cert',
  faDocDeploymentOrder: 'Document for all FAs — Deployment Order',
  visitorRegister: 'Visitor register (legacy)',
  keyRegister: 'Key register (legacy)',
  cashVaultRegister: 'Cash / Vault register (legacy)',
  atmRegister: 'ATM register (legacy)',
  patrolRegister: 'Patrol register (legacy)',
  complianceGapNotes: 'Compliance gap notes',
  mainEntranceDoor: 'Main Entrance Door',
  mainEntranceProcedure: 'Main door open / close procedure',
  shutterCondition: 'Shutter Condition',
  shutterOpenCloseProcedure: 'Shutter open / close procedure',
  windowsSecure: 'Windows secured',
  windowOpenCloseProcedure: 'Windows open / close procedure',
  entryPointsToBank: 'Entry Points to bank',
  openPosition: 'Normal Main door open position',
  backYardDoor: 'Back Yard door',
  damagedWindows: 'Damaged windows (could not be closed)',
  closingBankChecklist: 'Check list for closing Bank',
  whoLocksBank: 'Who Lock the bank',
  whoSealsKeys: 'Who will seal the keys',
  fireExtCount: 'No. of Fire extinguishers (legacy)',
  fireExtValidityChecked: 'Checked validity (legacy)',
  fireExtExpired: 'Expired Fire extinguishers (legacy)',
  strongRoomDoorClass: 'Strong Room — Class of Door (legacy)',
  strongRoomVentilator: 'Strong Room — Ventilator / Exhaust (legacy)',
  emergencyExit: 'Emergency Exit (legacy)',
  holidayOpeningPermission: 'Holiday openings — permission',
  holidayOpenCloseProcedure: 'Holiday open / close procedure',
  physicalSecurityNotes: 'Physical security notes',
  atmSite: 'ATM Site',
  atmCount: 'ATM count',
  atmShiftCount: 'No. of shift',
  atmKeySets: 'No. of key sets',
  atmOpenWiring: 'Open wiring',
  atmOpenPowerSocket: 'Open Power Socket',
  atmOpenConnection: 'ATM has Open Connection',
  faBelongingsInAtm: 'FAs belonging in ATM',
  atmDrawerContents: 'What is in ATM drawer',
  atmLobbyClean: 'ATM lobby is clean',
  unauthStickers: 'Unauthorised Stickers found',
  atmVisibleFromRoad: 'ATM can be seen from Road',
  surroundNightLighting: 'Surround Night Lightings',
  patrolBeforeTakeover: 'Patrolling system before takeover',
  atmAccessCount: 'No. of Access to ATM',
  canAccessBankFromAtm: 'Can they Access Bank from ATM',
  atmCctv: 'ATM CCTV',
  atmGuarding: 'ATM Guarding',
  generatorLocation: 'Generator Location',
  generatorVisibleFromAtm: 'Visibility from the ATM',
  generatorCctvCoverage: 'CCTV coverage to Generator',
  generatorAreaLuminated: 'Generator Area Luminated',
  generatorRegisterMaintained: 'Generator Register Maintained',
  atmLobbyAccess: 'Lobby access control',
  atmLobbyLighting: 'Lobby lighting',
  atmLobbyNotes: 'ATM / Lobby notes',
  generatorPresent: 'Generator present (legacy)',
  generatorBattery: 'Generator Battery',
  generatorLockIntact: 'Generator Lock is intact',
  generatorWorking: 'Generator working',
  generatorStartedBy: 'Who is starting the Generator',
  generatorDieselBy: 'Who is getting Diesel for Generator',
  generatorFuel: 'Fuel status',
  upsPresent: 'UPS present',
  upsBackupHours: 'UPS backup (hours)',
  utilityNotes: 'Utility notes',
  perimeterFence: 'Perimeter fence / wall',
  perimeterLighting: 'Perimeter lighting',
  cctvPerimeter: 'Perimeter CCTV',
  patrolFrequency: 'Patrol frequency',
  patrolRouteOk: 'Patrol route followed',
  outdoorAcUnit: 'Outdoor A/C Unit',
  outdoorAcLighting: 'Lightings Outdoor A/C Unit area',
  outdoorAcCctv: 'CCTV coverage to Outdoor A/C unit',
  patrolNotes: 'Patrol notes',
  feAtmCount: 'No. of FE in ATM',
  feAtmCo2: 'ATM FE — CO2',
  feAtmDcp: 'ATM FE — DCP',
  feAtmFoam: 'ATM FE — Foam',
  feAtmMixed: 'ATM FE — Mixed',
  feBankCount: 'No. of FE in Bank',
  feBankCo2: 'Bank FE — CO2',
  feBankDcp: 'Bank FE — DCP',
  feBankFoam: 'Bank FE — Foam',
  feBankMixed: 'Bank FE — Mixed',
  cookingHeatingAvailable: 'Cooking / Heating available',
  microwavePresent: 'Microwave',
  recentFireAudit: 'Recent Fire audit',
  recentFireDrill: 'Recent Fire Drill',
  fireExtinguisherType: 'Fire Extinguishers — Type (legacy)',
  fireExtinguisherQty: 'Fire Extinguishers — Quantity (legacy)',
  fireExtinguisherRefillDue: 'Refilling Due Date (legacy)',
  smokeDetectors: 'Smoke Detectors',
  fireAlarm: 'Fire Alarm',
  atmFireSafety: 'ATM fire safety OK',
  branchFireSafety: 'Branch fire safety OK',
  fireDrillDone: 'Fire drill done (legacy)',
  fireSafetyNotes: 'Fire safety notes',
  routerInstalled: 'Router installed',
  panicSwitchAtm: 'Panic switch availability in ATM',
  agileControlNumber: 'Agile Control Number',
  faKnowledgeAgileMobileAlarm: 'FA knowledge on Agile Mobile alarm',
  emergencyContactDisplayedFa: 'Emergency Contact Displayed / available with FA',
  escalationKnownFa: 'Escalation matrix Known to FA',
  panicSwitchCount: 'Panic Switches — Count (legacy)',
  panicSwitchStatus: 'Panic Switches — Status (legacy)',
  burglarAlarm: 'Burglar Alarm (legacy)',
  emergencyContactBank: 'Bank emergency contact',
  emergencyContactPolice: 'Police emergency contact',
  emergencyContactFire: 'Fire emergency contact',
  escalationKnown: 'Escalation matrix known to guards (legacy)',
  emergencyNotes: 'Emergency notes',
  cctvAtmCount: 'No. CCTV camera in ATM',
  cctvBankCount: 'No. of CCTV in Bank',
  localDvrLocation: 'Location of local DVR',
  cctvCableOpen: 'CCTV cable is open',
  cctvCameraCount: 'CCTV — Number of Cameras (legacy)',
  dvrNvrChannels: 'DVR / NVR — Channels',
  dvrNvrHdd: 'DVR / NVR — HDD capacity',
  recordingBackupDays: 'Recording Backup (days)',
  cctvCoverageOk: 'CCTV coverage adequate',
  electronicNotes: 'Electronic security notes',
  generalObservations: 'General Observations',
  hdfcRecommendations: 'Recommendations',
  surveyorSign: 'Surveyor Signature / Name',
  branchRepSign: 'Branch Representative Signature / Name',
}

export function hdfcFormSummaryLines(form: Record<string, string>): string[] {
  const lines: string[] = []
  for (const k of HDFC_FORM_KEYS) {
    if (k === 'clientPickHint') continue
    const v = (form[k] || '').trim()
    if (!v) continue
    lines.push(`${HDFC_FORM_LABELS[k] || k}: ${v}`)
  }
  return lines
}
