import type { VercelRequest, VercelResponse } from '@vercel/node'
import { sendSuiteEmail } from '../_lib/suite-mail.js'
import { Resend } from 'resend'
import { getLeads } from '../_lib/crm/store.js'
import { getUsers } from '../_lib/mis/store.js'

const IST_OFFSET_MIN = 5 * 60 + 30
function istNow(): Date {
  const utcMs = Date.now() + new Date().getTimezoneOffset() * 60000
  return new Date(utcMs + IST_OFFSET_MIN * 60000)
}
function weekStartMonday(d: Date): Date {
  const x = new Date(d)
  const wd = (x.getDay() + 6) % 7
  x.setDate(x.getDate() - wd)
  x.setHours(0, 0, 0, 0)
  return x
}
function esc(s: unknown) {
  return String(s ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}
function money(v: number) {
  return '₹' + (Number(v) || 0).toLocaleString('en-IN')
}

function section(title: string, rows: string[], closed = false) {
  const head = closed
    ? '<tr><th>Branch</th><th>Client</th><th>Manpower</th><th>Value</th><th>Deployment Date</th></tr>'
    : '<tr><th>Branch</th><th>Client</th><th>Manpower</th><th>Value</th><th>Remark</th></tr>'
  return `<h3 style="color:#14224f;border-left:5px solid #c9a84c;padding-left:10px;margin:18px 0 8px">${title} (${rows.length})</h3>
    <table style="border-collapse:collapse;width:100%;font-size:13px" border="1" cellpadding="6">
    <thead style="background:#14224f;color:#fff">${head}</thead>
    <tbody>${rows.join('') || '<tr><td colspan="5" style="color:#888">None this week.</td></tr>'}</tbody></table>`
}

async function buildReport(): Promise<{ subject: string; html: string }> {
  const leads = await getLeads()
  const ws = weekStartMonday(istNow()).getTime()
  const row = (l: any, closed = false) =>
    `<tr><td>${esc(l.branch)}</td><td>${esc(l.company)}</td><td>${esc(l.manpower)}</td><td>${money(l.estValue)}</td><td>${closed ? esc(l.deploymentDate) : esc(l.remarks)}</td></tr>`

  const isNew = (l: any) => new Date(l.createdAt || 0).getTime() >= ws
  const newLeads = leads.filter(isNew)
  const pipeline = leads.filter((l) => l.stage !== 'Won' && l.stage !== 'Lost')
  const hot = leads.filter((l) => l.stage === 'Negotiation' || l.stage === 'Quotation Sent')
  const closed = leads.filter((l) => l.stage === 'Won')

  const dateLabel = istNow().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })
  const html = `<div style="font-family:Arial,sans-serif;max-width:760px;margin:0 auto;color:#111">
    <div style="background:#14224f;color:#fff;padding:16px;border-radius:10px">
      <b style="font-size:18px">Agile CRM — Weekly Sales Report</b><div style="color:#c9a84c;font-size:13px">Week ending ${dateLabel}</div>
    </div>
    ${section('1. New Sales Leads (this week)', newLeads.map((l) => row(l)))}
    ${section('2. Sales Pipeline', pipeline.map((l) => row(l)))}
    ${section('3. Hot Sales Pipeline', hot.map((l) => row(l)))}
    ${section('4. Leads Closed (Won)', closed.map((l) => row(l, true)), true)}
    <p style="color:#888;font-size:12px;margin-top:16px">Auto-generated by Agile CRM every Saturday 3:00 PM.</p>
  </div>`
  return { subject: `Agile CRM — Weekly Sales Report (${dateLabel})`, html }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const now = istNow()
  const isSat = now.getDay() === 6
  const hour = now.getHours()
  const manual = String(req.query.job ?? '')
  let job = ''
  if (manual === 'report' || manual === 'reminder') job = manual
  else if (isSat && hour === 10) job = 'reminder'
  else if (isSat && hour === 15) job = 'report'

  if (!job) return res.status(200).json({ ok: true, skipped: true, reason: 'not a scheduled slot', ist: now.toISOString() })

  const apiKey = process.env.RESEND_API_KEY?.trim()
  if (!apiKey) return res.status(503).json({ error: 'Email not configured' })
  const resend = new Resend(apiKey)
  const from = process.env.EMAIL_FROM ?? 'Agile CRM <noreply@agilegroup.co.in>'

  try {
    if (job === 'reminder') {
      const users = await getUsers()
      const to = Array.from(new Set(users.filter((u) => u.active !== false && u.email.includes('@')).map((u) => u.email.trim())))
      to.push('director@agilegroup.co.in')
      await sendSuiteEmail(resend, {
        from,
        to: Array.from(new Set(to)),
        subject: 'Reminder: Update your CRM before 12:00 PM today (Saturday)',
        html: `<div style="font-family:Arial"><h3 style="color:#14224f">Weekly CRM Update Reminder</h3><p>Dear Team,</p><p>Please <b>update the CRM portal</b> — new leads, pipeline stage changes, follow-ups, and closed deals — <b>before 12:00 PM today (Saturday)</b>, so the Director's 3:00 PM weekly report is complete.</p><p>Open: <a href="https://www.agilegroup-digital.co.in/crm">www.agilegroup-digital.co.in/crm</a></p><p>— Agile CRM</p></div>`,
      })
      return res.status(200).json({ ok: true, job, remindedCount: to.length })
    }

    // report
    const { subject, html } = await buildReport()
    await sendSuiteEmail(resend, { from, to: ['director@agilegroup.co.in'], subject, html })
    return res.status(200).json({ ok: true, job })
  } catch (e) {
    return res.status(502).json({ error: e instanceof Error ? e.message : 'send failed' })
  }
}
